### PR TITLE
Make description little bit more verbose

### PR DESCRIPTION
**Pull request by LukasReschke**
So that it looks nicer in the App settings.

Before:
screen shot 2015-01-17 at 01 11 20

After:
screen shot 2015-01-17 at 01 10 44
@carlaschroder Please review my English. If you find any mistakes or improvements feel free to directly edit this in this branch.

### CODE REVIEW

**Comment by LukasReschke** [comment]
(the ugly formatting of the Provisoning API is btw. also fixed on master in core – didn't pull at the time of the first screenshot)

**Comment by LukasReschke** [comment]
@DeepDiver1975 I removed the large list of PDF.js contributors as it makes not really much sense to add it there (besides the fact that this list is nowadays even longer). Instead I added a hint about the project in the description. Is that okay for you? You added those end-2012 with https://github.com/owncloud/files_pdfviewer/commit/d6f6a0148f68c4f31f8d9f9aac4f4b7663eb2fe4

**Comment by carlaschroder** [comment]
:+1:   I approved, this is much improved.

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
