### PR TITLE
Add back close button

### PR DESCRIPTION
**Pull request by LukasReschke**
@MorrisJobke Small security hardening and also adds back the close button

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Looks bit broken:

bildschirmfoto 2015-12-07 um 15 32 17

**Comment by LukasReschke** [comment]
Grmpfl. What browser? Works here on Chrome :speak_no_evil:

**Comment by MorrisJobke** [comment]
> Grmpfl. What browser? Works here on Chrome

Chrome on low res display (1080p - 23")

**Comment by LukasReschke** [comment]
Fair enough. Let me check that tomorrow. No low res screen here :speak_no_evil:

**Pull request merged**
