### PR TITLE
Fix for IE to remove second scrollbar

### PR DESCRIPTION
**Pull request by PVince81**
- [x] REQUIRES: https://github.com/owncloud/core/pull/22561

The fix above is needed to make the footer work in IE. However it introduces a second scrollbar due to the "new" layout configuration.

This fix sets the "display" property back when using the PDF viewer.

### CODE REVIEW

**Comment by PVince81** [comment]
Please review @Henni @LukasReschke @icewind1991

**Comment by PVince81** [comment]
@karlitschek backport to stable8.2 ? (it's the PDF viewer counterpart of https://github.com/owncloud/core/pull/22561)

**Comment by karlitschek** [comment]
please backport :+1:

**Comment by PVince81** [comment]
stable8.2: https://github.com/owncloud/files_pdfviewer/pull/99

**Comment by PVince81** [comment]
@LukasReschke @MorrisJobke second review ? (core was merged)

**Comment by LukasReschke** [comment]
Works here :100:

**Pull request merged**
