### PR TITLE
Fix context menu entry

### LINKED ISSUE #226: Context menu, wrong name and missing icon
### Description
1. Display name is wrong: "favorite"
2. Icon is missing
3. name is not specific and could compete with another app with the same generic name

### PR DESCRIPTION
**Pull request by JanAckermann**
### Description
1. Display name is wrong: "favorite"
2. Icon is missing
3. name is not specific and could compete with another app with the same generic name 

Fixes #226

### CODE REVIEW

**Review by mrow4a — CHANGES_REQUESTED** [review]
I block this PR as it might need strong review. For legacy reasons this “view” keyword can be used around .. just not to break something

**Comment by HieronymusPerro** [comment]
> For legacy reasons this “view” keyword can be used around .. just not to break something

I am not pretty sure about this, if you have to apps which register actions with the name view, they will overlap and you can't be sure which will be selected, as well you can't have two entries in the context menu.

**Comment by mrow4a** [comment]
legacy with years old code... I will just have a look to be sure

**Comment by mmattel** [comment]
Hi, any news on that?

**Review by mrow4a — APPROVED** [review]

**Pull request merged**
