### PR TITLE
Merge back Release 0.11.1

### PR DESCRIPTION
**Pull request by micbar**

### CODE REVIEW

**Comment by micbar** [comment]
@phil-davis Seems that we have a merge conflict now.

**Comment by phil-davis** [comment]
We probably need to cherry-pick some phpunit-related commits from master.
@micbar should I do that now? Or wait until you have made the final 0.11.1 release from this branch?

**Comment by phil-davis** [comment]
I cherry-picked the 5 commits from master that changed test/CI infrastructure in the last weeks. That gets rid of the conflict message. None of that effects the real app code.

**Comment by jnweiger** [comment]
Closes #197

**Pull request merged**
