### PR TITLE
Add transifex

### PR DESCRIPTION
**Pull request by JanAckermann**

### CODE REVIEW

**Comment by JanAckermann** [comment]
@micbar is there something more todo?

**Comment by micbar** [comment]
yes. We need to check a makefile target and create the transifex project.

@pmaier1 

IMO this is currently not a high prio for 10.7. we could do this after the core release.

**Comment by JanAckermann** [comment]
@kulmann Makefile adjusted, can you create a transifex project ? :+1:

**Comment by JanAckermann** [comment]
@micbar @kulmann approve please :)

**Review by kulmann — APPROVED** [review]
LGTM
Next you will need to add this repo to the `translation-sync` repo

**Pull request merged**
