### PR TITLE
Backport of #91 - Fix regression introduced by 72069f4

### PR DESCRIPTION
**Pull request by Henni**
backport of #91 for stable8.2

### CODE REVIEW

**Comment by jancborchardt** [comment]
@fuerst @mecias please review this backport too! :)

**Comment by MeCias** [comment]
@jancborchardt thanks a lot. I can confirm that the backport works as well. Like a charm! :)

**Comment by LukasReschke** [comment]
:+1:

**Comment by jancborchardt** [comment]
@Henni @DeepDiver1975 what about the Travis failure?

**Comment by PVince81** [comment]
Looks like this doesn't work in IE9 and IE11 :frowning:

**Comment by PVince81** [comment]
The footer appears in the middle as before

**Comment by PVince81** [comment]
Turns out that disabling the PDF viewer doesn't help either, must be yet another issue in core.

**Pull request merged**
