### PR TITLE
[stable8.2] Redirect page if not shown in an iframe

### PR DESCRIPTION
**Pull request by LukasReschke**

### CODE REVIEW

**Comment by PVince81** [comment]
PDF viewer still works :+1:

**Comment by PVince81** [comment]
@LukasReschke 8.2 only ?

Second reviewer ? @nickvergessen @icewind1991 @rullzer @blizzz

**Comment by nickvergessen** [comment]
See PRs 108-113 ?

**Comment by PVince81** [comment]
Right, thanks for the pointers

**Comment by nickvergessen** [comment]
:+1:

**Comment by nickvergessen** [comment]
oracle failure is normal

**Comment by davitol** [comment]
:+1: tested and WFM

**Pull request merged**
