### PR TITLE
Remove white area below pdf viewer on public page

### PR DESCRIPTION
**Pull request by Henni**
fixes owncloud/core#20557

comment on diff: I moved `style.css` to `viewer.css` and added a new `style.css`

Please review @LukasReschke @PVince81 @owncloud/designers

### CODE REVIEW

**Comment by PVince81** [comment]
:+1: tested, works

**Comment by PVince81** [comment]
@Henni there are conflicts. Maybe you forgot to pull master when creating this branch ?
Can you rebase it ?

**Comment by jancborchardt** [comment]
This also needs a backport, right? It’s a pretty ugly bug in 8.2

**Comment by jancborchardt** [comment]
This also needs a backport, right? It’s a pretty ugly bug in 8.2 cc @karlitschek

**Comment by karlitschek** [comment]
i agreee. a backport would be great

**Comment by Henni** [comment]
rebased...
I'm working on the backport

**Comment by PVince81** [comment]
Still works after rebase :+1:

**Comment by Henni** [comment]
Backport at #88

**Comment by LukasReschke** [comment]
:+1:

**Comment by brozkeff** [comment]
Apparently this minor visual fix is causing more severe unusability of public links with many files - https://github.com/owncloud/files_pdfviewer/issues/90

I'd consider white are as less evil than the cannot-scroll-issue 90.

**Comment by jancborchardt** [comment]
@Henni can you check out that regression? Would be cool if we don't need to revert. Cc @owncloud/designers

**Comment by Henni** [comment]
@jancborchardt I'm on it

**Pull request merged**
