### PR TITLE
[Tests-Only][CI] fix the starlark code for reduced ci after merge and sonarcloud

### PR DESCRIPTION
**Pull request by dpakach**
fix the starlark code for reduced ci after merge and sonarcloud

issue https://github.com/owncloud/QA/issues/649

### CODE REVIEW

**Comment by mmattel** [comment]
Sonarcloud is failing... 😢

**Comment by phil-davis** [comment]
We have to add `sonar_token` to the drone repo, and create the project in SonarCloud etc. Then restart CI. The same applies to the other pile of PRs that @dpakach created this morning in the oC10 app repos.

**Comment by mmattel** [comment]
@dpakach still issuing
`Sonarcloud: ERROR: Could not find a default branch to fall back on.`

**Comment by mmattel** [comment]
hmmm, still `finding no default branch fallback` error.
Maybe to use the `-X` switch temporarily to get more details

**Comment by phil-davis** [comment]
I had a typo in the SonarCloud project name! I fixed it now and restarted drone CI - let's see what happens.

**Review by phil-davis — APPROVED** [review]

**Comment by phil-davis** [comment]
A previous PR #229 has 73% coverage and SonarCloud also says 73% :+1:

**Pull request merged**
