### PR TITLE
Update pdfjs to version v1.4.20

### PR DESCRIPTION
**Pull request by PVince81**
Fixes https://github.com/owncloud/files_pdfviewer/issues/107

### CODE REVIEW

**Comment by PVince81** [comment]
It doesn't work because we need to override `PDFJS.workerSrc` to the correct URL.
While pdf.js accepts the value, the later viewer.js that runs once the viewer starts will ignore the value and override it in its `configure(PDFJS)` method.

Maybe something changed in the loading order or maybe we need to put our workerSrc override at a later point, not sure how. Would need to find an event to override the config.

**Comment by PVince81** [comment]
Okay, I hacked the viewer.js to accept our config: https://github.com/owncloud/files_pdfviewer/pull/126/commits/c7e806ab4b7c0f2d8a29929caf67428c60e5af2b

I have the feeling that this viewer.html was never intended to be used the way we do it. Also from what I see we anyway had to inject the viewer.html stuff into our own viewer.php, so this all doesn't go without a bit of patching.

Please review @DeepDiver1975 @butonic

**Comment by butonic** [comment]
👍 tested in firefox, chrome and ie11

**Comment by butonic** [comment]
@yurydelendik @michaelstingl care to review this PDFjs update ?

**Comment by michaelstingl** [comment]
@butonic Which oC version do I need to test this? I just tried to replace `app/files_pdfviewer/` in my 9.1.1, but it didn't worked.

**Comment by butonic** [comment]
Master ;)

Am 23. September 2016 22:52:34 MESZ, schrieb Michael Stingl <notifications@github.com>:
>@butonic Which oC version do I need to test this? I just tried to
>replace `app/files_pdfviewer/` in my 9.1.1, but it didn't worked.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/owncloud/files_pdfviewer/pull/126#issuecomment-249299547

--
Dr. Jörn Friedrich Dreyer
Solutions Architect
ownCloud GmbH

Your Data, Your Cloud, Your Way!

ownCloud GmbH, GF: Markus Rex, Holger Dyroff
Schloßäckerstrasse 26a, 90443 Nürnberg, HRB 28050 (AG Nürnberg)

**Comment by yurydelendik** [comment]
> care to review this PDFjs update ?

The change at c7e806ab4b7c0f2d8a29929caf67428c60e5af2b looks good. I think you can change the hardcoded path to use your own instead.

**Comment by PVince81** [comment]
@yurydelendik this is done in a separate location already and used to work in past pdfjs versions. I didn't want to introduce OC-specific code inside the vendor folder.

**Comment by PVince81** [comment]
Thanks for the testing, guys. Merging

**Pull request merged**
