### PR TITLE
Prevent working with IE below 9

### PR DESCRIPTION
**Pull request by LukasReschke**
Fixes https://github.com/owncloud/files_pdfviewer/issues/54

cc @PVince81 :see_no_evil: Inputs?

### CODE REVIEW

**Comment by LukasReschke** [comment]
@SergioBertolinSG Please test. THX.

**Comment by PVince81** [comment]
You mean the PDF library doesn't work in IE8 ?

**Comment by SergioBertolinSG** [comment]
Tested this branch, now the file is downloaded instead of trying to be shown.
Ok if we give up to open pdfs in ie8.
(Tested also in ie9, working fine)

**Comment by LukasReschke** [comment]
> You mean the PDF library doesn't work in IE8 ?

Yes. As it is documented in appinfo.xml and on the upstream page. Version 7 had this check and with the 8.0 refactoring this somehow got lost :see_no_evil:

**Comment by PVince81** [comment]
Well then :+1:

**Pull request merged**
