### PR TITLE
Pdfjs update

### PR DESCRIPTION
**Pull request by jvillafanez**
Update pdfjs to 2.5. It should fix https://github.com/owncloud/enterprise/issues/4280

We'll likely need a test build to verify.

Note: the pdfjs has been built with node v10.23.0 due to problems with later versions regarding a dependency with canvas@2.6.1

### CODE REVIEW

**Comment by mmattel** [comment]
Hi @jvillafanez any news on that?

**Comment by jvillafanez** [comment]
No news from my side.

I'm not the one building and releasing the app, so I can't guarantee this will break things, specially with the difficulties I've had. I'm not buying a "it works for me" even from myself.
There could be problems in the build which could affect to the goal of improving the quality of the PDF's images, which is the reason to upgrade the library.

**Comment by mmattel** [comment]
@HanaGemela (cc @phil-davis) may I ask you for your support. You helped a lot in files_mediaviewer. I do not know whom else to ask ...

**Review by VicDeo — APPROVED** [review]
Works for me.
As I see they switched to es6-compatible build by default: 
>v2.4.456
From now on we produce a non-translated/non-polyfilled build for modern browsers by default. However, we also provide the translated/polyfilled build for older browsers in a separate bundle (with the -es5-dist.zip suffix).

Does it affect our app and is it ok if it does?

**Comment by jvillafanez** [comment]
Translations doesn't seem to work for me. pdfjs still shows in English even though ownCloud is in a different language. The locale set during initialization is the right one. Not sure if we're setting it wrong, or late, or the translations are missing in the package.

**Comment by mmattel** [comment]
> Translations doesn't seem to work for me. pdfjs still shows in English even though ownCloud is in a different language. The locale set during initialization is the right one. Not sure if we're setting it wrong, or late, or the translations are missing in the package.

Does it work before this PR?

**Comment by jvillafanez** [comment]
> Translations doesn't seem to work for me. pdfjs still shows in English even though ownCloud is in a different language. The locale set during initialization is the right one. Not sure if we're setting it wrong, or late, or the translations are missing in the package.

There is a weird redirection that prevents the browser to get the locate.properties files, so it can't translate the screen. Fixing the redirection make the app work properly.
Nothing to do here.

**Comment by jvillafanez** [comment]
> Does it work before this PR?

Not for me, but as said, it's a setup problem. This PR won't break the translations.

**Comment by mmattel** [comment]
> Fixing the redirection makes the app work properly.
Nothing to do here.

Means you can merge now :smile:
Means, that you know where to fix this separate issue and could quickly create an additional PR for this? 😄

**Comment by phil-davis** [comment]
Release issue is #230

**Pull request merged**
