### PR TITLE
Enhance canDownload notification text

### PR DESCRIPTION
**Pull request by JanAckermann**
see https://github.com/owncloud/files_pdfviewer/pull/234#issuecomment-747456930

### CODE REVIEW

**Review by mmattel — APPROVED** [review]

**Comment by phil-davis** [comment]
drone fails at sync-from-cache for doing SonarCloud Analysis because of https://github.com/minio/mc/issues/3538

`minio/mc` published a new but broken docker image a few hours ago. If they do not fix it "soon" then we will need to pin to an old tag.

**Comment by mmattel** [comment]
omg 🤦‍♂️ ...

**Comment by phil-davis** [comment]
@JanAckermann PR #238 hs been merged - it fixed CI.

Please rebase this PR and it should pass.

**Comment by JanAckermann** [comment]
https://drone.owncloud.com/owncloud/files_pdfviewer/875

```

$ wget -qO- https://download.owncloud.org/community/owncloud-daily-master-qa.tar.bz2 \| tar -xj -C /tmp/owncloud/ --strip 1
--
5 |  
6 | bzip2: Compressed file ends unexpectedly;

```

**Comment by phil-davis** [comment]
Just lucky? I can fetch the daily tarball OK from my desktop.

**Pull request merged**
