### PR TITLE
Change pdfjs v2.5 to es5 version to keep up with IE11 

### PR DESCRIPTION
**Pull request by JanAckermann**

### CODE REVIEW

**Comment by jvillafanez** [comment]
It doesn't seem to work with firefox and chrome: 
Screenshot from 2021-04-07 12-57-12

**Comment by jvillafanez** [comment]
In addition, try to use 2 different commits, one for the library update and another one for the code changes on our side. It should be easier to review.

**Comment by JanAckermann** [comment]
I don't have any issues here either with FF or Chrome.
image

@JammingBen on your side?

**Comment by jvillafanez** [comment]
It seems to work now in firefox and chrome. I haven't checked other browsers.

I find it weird that I had the same change set and it wasn't working when I was trying to fix it...

**Review by jvillafanez — APPROVED** [review]

**Comment by JanAckermann** [comment]
@jvillafanez good 👍 I will do a backport for current Release so qa will Test all browsers

**Comment by JanAckermann** [comment]
Btw Up 2.7 no es5 Support 
Fyi @phil-davis

**Comment by jvillafanez** [comment]
I think we'll have to change the "generic-es5" to "generic-legacy" for 2.8 (for the next time we upgrade the library). I don't know if we'll have to make more changes.

**Pull request merged**
