### PR TITLE
Fix regression introduced by 72069f4

### LINKED ISSUE #90: scrolling file lists in public share greater than windows size not possible
Commit 72069f4e20a7d10fa81f3c19703f8ca895ac8867 introduced a 100% heigth in *css/style.css*. This makes scrolling file lists larger than windows size impossible.

OC Version 8.2.2 EE

**Steps to reproduce**
* create folder
* share folder via link
* create a lot of files / folders in the shared folder
* visit the public link with a separate browser and reduce windows height

The list items cannot be scrolled which makes the last entries unavailable.

**Quick solution**
Uncomment line 3 in css/style.css. The file list is scrollable again but the white border at the bottom in pdf preview will reappear. You can also disable the files_pdfviewer app if you cannot modifiy files.

### PR DESCRIPTION
**Pull request by Henni**
fixes #90 

please review @LukasReschke @roha4000 @mhzawadi @brozkeff @fuerst

### CODE REVIEW

**Comment by MorrisJobke** [comment]
@karlitschek We should backport this ;)

**Comment by fuerst** [comment]
- Vertical scrolling fixed in file lists accessed by public share link.
- PDF file is displayed with full windows height - no white padding at bottom.

Works - thanks!

**Comment by MorrisJobke** [comment]
@hechi The brown labels are for back ports: https://doc.owncloud.org/server/9.0/developer_manual/general/backporting.html?highlight=backport#process

**Comment by karlitschek** [comment]
please backport :+1:

**Comment by Henni** [comment]
backport on top of tag `v8.2.2` ?

**Comment by nickvergessen** [comment]
@Henni branch stable8.2: https://github.com/owncloud/files_pdfviewer/tree/stable8.2

**Comment by MeCias** [comment]
Can confirm that it works in 8.2.2. Thanks for that.

**Comment by Henni** [comment]
@nickvergessen thanks. I'm on it

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
