### PR TITLE
Bump pdf.js to 2.1.0

### PR DESCRIPTION
**Pull request by VicDeo**
Ref https://github.com/owncloud/files_pdfviewer/issues/183

- [x] fix workerSrc
- [x] test locale detection for regressions

### CODE REVIEW

**Comment by micbar** [comment]
Looks good to me.
@cdamken Could you test?

**Comment by micbar** [comment]
@cdamken @VicDeo I would like somebody to test it first. We have no acceptance tests here.

**Comment by davitol** [comment]
It does not solve the issue related to embedded linked pdfs are not accessible

Screen Shot 2019-07-01 at 13 11 43


Using the test file posted here: https://github.com/owncloud/enterprise/issues/3377#issuecomment-501295915

It opens a new tab
with a link like ```'http://myserver/apps/files_pdfviewer/?file=blob:http://10.40.40.222:9681/901df9d3-6e58-744f-b93f-5f7897f9b758#1_0900609767_PDFA.pdf```
loads blank page until it redirects to ```http://myserver/apps/files/``` again
```"?file=blob%3Ahttp%3A%2F%2F10.40.40.222%3A9681%2Faee771a8-d1a3-4f7b-a453-c30b609c0186%231_0900609767_PDFA.pdf"``` is what is trying to open

**Comment by davitol** [comment]
Not sure if related or not but Close cross appears bigger than in previous pdf versions:

Screen Shot 2019-07-01 at 14 19 07
Screen Shot 2019-07-01 at 14 20 12

**Comment by davitol** [comment]
## 'PDF Viewer' Test Plan

- Run Testplan with all supported browsers: Internet Explorer 11, MS EDGE, Mozilla Firefox, Chrome and Safari.

Note: testplan has been run with Firefox and Chrome

## Testing functionality

Test Case | Expected Result | Result | Related Comment
------------- | -------------- | ----- | ------
**CLI commands** |  |   |
|  |   |
Enable files_pdfviewer app via CLI using ```occ app:enable files_pdfviewer``` | The apps gets enabled | :+1:  |
Disable files_pdfviewer app via CLI using ```occ app:disable files_pdfviewer``` | The apps gets disabled | :+1:  |
**Files View** |  |   |
|  |   |
Open a pdf file | The content is shown and pdf filesviewer buttons work (download, thumbnails, fwd page...) | :+1:  |
**Favorites section** |  |   |
|  |   |
Make favorite a pdf file and open it from favorite section| The content is shown and pdf filesviewer buttons work (download, thumbnails, fwd page...) | :+1:  |
**Share with you section** |  |   |
Receive a pdf file and open it from share with you section| The content is shown and pdf filesviewer buttons work (download, thumbnails, fwd page...) | :+1:  |
**Share with others section**|  |   |
|  |   |
Share a pdf file and open it from share with others section| The content is shown and pdf filesviewer buttons work (download, thumbnails, fwd page...) | :+1:  |
**Share by link section**|  |   |
|  |   |
Share a pdf file via link and open it from share by link section| The content is shown and pdf filesviewer buttons work (download, thumbnails, fwd page...) | :+1:  |
**Tag section**|  |   |
|  |   |
Tag a pdf file and search for tag and open it from tag section| The content is shown and pdf filesviewer buttons work (download, thumbnails, fwd page...) | :+1:  |
**Public link**|  |   |
|  |   |
Share a pdf file via link and open it from the link| The content is shown and pdf filesviewer buttons work (download, thumbnails, fwd page...) | :+1:  | see https://github.com/owncloud/files_pdfviewer/issues/180 for minor issue that is not a regression
**External Storage**|  |   |
|  |   |
Open a pdf file located in an external storage | The content is shown and pdf filesviewer buttons work (download, thumbnails, fwd page...) | :+1:  |
**Guest App**|  |   |
|  |   |
Open a pdf file using a guest user | The content is shown and pdf filesviewer buttons work (download, thumbnails, fwd page...) | :+1:  |
**Impersonate App**|  |   |
|  |   |
Open a pdf file using an impersonated user | The content is shown and pdf filesviewer buttons work (download, thumbnails, fwd page...) | :+1:  |

**Comment by VicDeo** [comment]
>It opens a new tab
with a link like 'http://myserver/apps/files_pdfviewer/?file=blob:http://10.40.40.222:9681/901df9d3-6e58-744f-b93f-5f7897f9b758#1_0900609767_PDFA.pdf
loads blank page until it redirects to http://myserver/apps/files/ again
"?file=blob%3Ahttp%3A%2F%2F10.40.40.222%3A9681%2Faee771a8-d1a3-4f7b-a453-c30b609c0186%231_0900609767_PDFA.pdf" is what is trying to open

yes.  After unescaping the entities the URL looks like `?file=blob:http://localhost/e8373c23-87e5-4377-9547-ff0a7ccf8f21;5_0900613353_PDFA.pdf`
and `blob:` inside the URL clearly indicates that pdf viewer component tries to access the current page content... needs debugging/development

**Comment by VicDeo** [comment]
> Close cross appears bigger than in previous pdf versions:

@davitol On retina display?

**Comment by davitol** [comment]
> > Close cross appears bigger than in previous pdf versions:
> 
> @davitol On retina display?

Regular devices.

**Comment by micbar** [comment]
@VicDeo Could you address the icon size?
Could you give me an effort estimation for a complete fix?

**Comment by VicDeo** [comment]
@micbar it's kinda "fixed" because I explicitly restyled "Close" button in this PR. This is how it looks for me:

Close

>an effort estimation for a complete fix?

it's hard to say as I don't know pdf.js internals too close.  Let's say 2-3 md

**Comment by pmaier1** [comment]
PDF.js 2.1 seems to be stable now: https://github.com/owncloud/files_pdfviewer/issues/183#issuecomment-511336101

**Pull request merged**
