### PR TITLE
[WIP] Use injected file list

### PR DESCRIPTION
**Pull request by LukasReschke**
@PVince81

### CODE REVIEW

**Comment by LukasReschke** [comment]
(Needs a backport to 8)

**Comment by LukasReschke** [comment]
Causes the same problem when going to the Favorites, then clicking on a PDF, then going to the regular files and opening a PDF there.

**Comment by PVince81** [comment]
Ah yes, this is because you are using the same plugin instance for different file lists.

You need to get the FileList instance in the action handler, as `context.fileList` and then pass it to whichever code needs it. (or barbarically just set it into the plugin's attribute, it will change every time but would work)

**Comment by jancborchardt** [comment]
@LukasReschke @PVince81 what’s the status of this? Merge or kill?

**Pull request closed without merging**
